//
//  MainViewController.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import UIKit
import AWSMobileHubHelper

class MainTabController: UITabBarController {
   
    var tabItems: [TabBarHelper] = []
    var signInObserver: AnyObject!
    var signOutObserver: AnyObject!
    var willEnterForegroundObserver: AnyObject!
    fileprivate let loginButton: UIBarButtonItem = UIBarButtonItem(title: nil, style: .done, target: nil, action: nil)
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // tabItem represents the object of one of the three tabs
        var tabItem = TabBarHelper.init(
            name: "Home",
            icon: "HomeTabIcon",
            storyboard: "Home",
            title: "Home"
        )
        tabItems.append(tabItem)
        
        tabItem = TabBarHelper.init(
            name: "My Reps",
            icon: "MyRepsTabIcon",
            storyboard: "MyReps",
            title: "My Representatives"
        )
        tabItems.append(tabItem)
        
        tabItem = TabBarHelper.init(
            name: "Me",
            icon: "MeTabIcon",
            storyboard: "Me",
            title: "Me"
        )
        tabItems.append(tabItem)
        
        
        // Use this method to update theme or other settings with the users last setting,
        // Unless we want to setup some navigation items, nothing much needs to happen here,
        // But in the other class, they setup the Sign-In/Sign-Button in the sample app's main table
        signInObserver = NotificationCenter.default.addObserver(forName: NSNotification.Name.AWSIdentityManagerDidSignIn, object: AWSIdentityManager.default(), queue: OperationQueue.main, using: {[weak self] (note: Notification) -> Void in
            guard let strongSelf = self else { return }
            print("Sign In Observer observed sign in.")
            
            
            
        })
        
        // Similar to above method
        signOutObserver = NotificationCenter.default.addObserver(forName: NSNotification.Name.AWSIdentityManagerDidSignOut, object: AWSIdentityManager.default(), queue: OperationQueue.main, using: {[weak self](note: Notification) -> Void in
            guard let strongSelf = self else { return }
            print("Sign Out Observer observed sign out.")
            
            
            
        })
        
        // Set up any navigation bar items or otherwise here, but we don't necessarily need one 
        // Since this section just sets up the main table view's Sign-In/Sign-Out button
        
        
        
    }
    
    deinit {
        NotificationCenter.default.removeObserver(signInObserver)
        NotificationCenter.default.removeObserver(signOutObserver)
    }
    
    func presentSignInViewController() {
        if !AWSIdentityManager.default().isLoggedIn {
            let storyboard = UIStoryboard(name: "SignIn", bundle: nil)
            let viewController = storyboard.instantiateViewController(withIdentifier: "SignIn")
            self.present(viewController, animated: true, completion: nil)
        }
    }
    
    // MARK: - UITabBarController delegates
    
    override func setViewControllers(_ viewControllers: [UIViewController]?, animated: Bool) {
        
        
        
    }
    
    public func tabBarController(_ tabBarController: UITabBarController, didSelect viewController: UIViewController) {
        
        
        
    }
    
    func handleLogout() {
        if (AWSIdentityManager.default().isLoggedIn) {
            AWSIdentityManager.default().logout(completionHandler: {(result: Any?, error: Error?) in
                self.navigationController!.popToRootViewController(animated: false)
                self.presentSignInViewController()
            })
            // print("Logout Successful: \(signInProvider.getDisplayName)");
        } else {
            assert(false)
        }
    }
    
}


class MainViewController: UITableViewController {
    
    var demoFeatures: [DemoFeature] = []
    var signInObserver: AnyObject!
    var signOutObserver: AnyObject!
    var willEnterForegroundObserver: AnyObject!
    fileprivate let loginButton: UIBarButtonItem = UIBarButtonItem(title: nil, style: .done, target: nil, action: nil)
    
    // MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "Back", style: .plain, target: nil, action: nil)
        
        // You need to call `- updateTheme` here in case the sign-in happens before `- viewWillAppear:` is called.
//        updateTheme()
        willEnterForegroundObserver = NotificationCenter.default.addObserver(forName: NSNotification.Name.UIApplicationWillEnterForeground, object: nil, queue: OperationQueue.current) { _ in
//            self.updateTheme()
        }

            presentSignInViewController()
        
        var demoFeature = DemoFeature.init(
            name: NSLocalizedString("User Sign-in",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("Enable user login with popular 3rd party providers.",
                comment: "Description for demo menu option."),
            icon: "UserIdentityIcon", storyboard: "UserIdentity")
        
        demoFeatures.append(demoFeature)
        
//        demoFeature = DemoFeature.init(
//            name: NSLocalizedString("App Content Delivery",
//                comment: "Label for demo menu option."),
//            detail: NSLocalizedString("Store and distribute media assets and other files via global content delivery network.",
//                comment: "Description for demo menu option."),
//            icon: "ContentDeliveryIcon", storyboard: "ContentDelivery")
//        
//        demoFeatures.append(demoFeature)
//        
//        demoFeature = DemoFeature.init(
//            name: NSLocalizedString("User Data Storage",
//                comment: "Label for demo menu option."),
//            detail: NSLocalizedString("Save user files in the cloud and sync user data in key/value pairs.",
//            comment: "Description for demo menu option."),
//            icon: "UserFilesIcon", storyboard: "UserDataStorage")
//        
//        demoFeatures.append(demoFeature)
//        
//        demoFeature = DemoFeature.init(
//            name: NSLocalizedString("User Engagement",
//                comment: "Label for demo menu option."),
//            detail: NSLocalizedString("Analyze app usage, define segments, create and measure campaign metrics.",
//            comment: "Description for demo menu option."),
//            icon: "Engage", storyboard: "Engage")
//        
//        demoFeatures.append(demoFeature)
//
//        demoFeature = DemoFeature.init(
//            name: NSLocalizedString("Cloud Logic",
//                comment: "Label for demo menu option."),
//            detail: NSLocalizedString("Run business logic in the cloud without managing servers. Integrate functionality with your app using APIs.",
//                comment: "Description for demo menu option."),
//            icon: "CloudLogicAPIIcon", storyboard: "CloudLogicAPI")
//        
//        demoFeatures.append(demoFeature)
        
        demoFeature = DemoFeature.init(
            name: NSLocalizedString("NoSQL",
                comment: "Label for demo menu option."),
            detail: NSLocalizedString("Store data in the cloud.",
                comment: "Description for demo menu option."),
            icon: "NoSQLIcon", storyboard: "NoSQLDatabase")
        
        demoFeatures.append(demoFeature)

                signInObserver = NotificationCenter.default.addObserver(forName: NSNotification.Name.AWSIdentityManagerDidSignIn, object: AWSIdentityManager.default(), queue: OperationQueue.main, using: {[weak self] (note: Notification) -> Void in
                        guard let strongSelf = self else { return }
                        print("Sign In Observer observed sign in.")
                        strongSelf.setupRightBarButtonItem()
                        // You need to call `updateTheme` here in case the sign-in happens after `- viewWillAppear:` is called.
//                        strongSelf.updateTheme()
                })
                
                signOutObserver = NotificationCenter.default.addObserver(forName: NSNotification.Name.AWSIdentityManagerDidSignOut, object: AWSIdentityManager.default(), queue: OperationQueue.main, using: {[weak self](note: Notification) -> Void in
                        guard let strongSelf = self else { return }
                        print("Sign Out Observer observed sign out.")
                        strongSelf.setupRightBarButtonItem()
//                        strongSelf.updateTheme()
                })
                
                setupRightBarButtonItem()
    }
    
    deinit {
        NotificationCenter.default.removeObserver(signInObserver)
        NotificationCenter.default.removeObserver(signOutObserver)
        NotificationCenter.default.removeObserver(willEnterForegroundObserver)
    }

    func setupRightBarButtonItem() {
            navigationItem.rightBarButtonItem = loginButton
            navigationItem.rightBarButtonItem!.target = self
            
            if (AWSIdentityManager.default().isLoggedIn) {
                navigationItem.rightBarButtonItem!.title = NSLocalizedString("Sign-Out", comment: "Label for the logout button.")
                navigationItem.rightBarButtonItem!.action = #selector(MainViewController.handleLogout)
            }
    }
    
    func presentSignInViewController() {
        if !AWSIdentityManager.default().isLoggedIn {
            let storyboard = UIStoryboard(name: "SignIn", bundle: nil)
            let viewController = storyboard.instantiateViewController(withIdentifier: "SignIn")
            self.present(viewController, animated: true, completion: nil)
        }
    }
    
    // MARK: - UITableViewController delegates
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "MainViewCell")!
        let demoFeature = demoFeatures[indexPath.row]
        cell.imageView!.image = UIImage(named: demoFeature.icon)
        cell.textLabel!.text = demoFeature.displayName
        cell.detailTextLabel!.text = demoFeature.detailText
        return cell
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return demoFeatures.count
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        let demoFeature = demoFeatures[indexPath.row]
        let storyboard = UIStoryboard(name: demoFeature.storyboard, bundle: nil)
        let viewController = storyboard.instantiateViewController(withIdentifier: demoFeature.storyboard)
        self.navigationController!.pushViewController(viewController, animated: true)
    }

//    func updateTheme() {
//        let settings = ColorThemeSettings.sharedInstance
//        settings.loadSettings { (themeSettings: ColorThemeSettings?, error: Error?) -> Void in
//            guard let themeSettings = themeSettings else {
//                 print("Failed to load color: \(error)")
//                return
//            }
//            DispatchQueue.main.async(execute: {
//                let titleTextColor: UIColor = themeSettings.theme.titleTextColor.UIColorFromARGB()
//                self.navigationController!.navigationBar.barTintColor = themeSettings.theme.titleBarColor.UIColorFromARGB()
//                self.view.backgroundColor = themeSettings.theme.backgroundColor.UIColorFromARGB()
//                self.navigationController!.navigationBar.tintColor = titleTextColor
//                self.navigationController!.navigationBar.titleTextAttributes = [NSForegroundColorAttributeName: titleTextColor]
//            })
//        }
//    }
    
    
    func handleLogout() {
        if (AWSIdentityManager.default().isLoggedIn) {
//            ColorThemeSettings.sharedInstance.wipe()
            AWSIdentityManager.default().logout(completionHandler: {(result: Any?, error: Error?) in
                self.navigationController!.popToRootViewController(animated: false)
                self.setupRightBarButtonItem()
                    self.presentSignInViewController()
            })
            // print("Logout Successful: \(signInProvider.getDisplayName)");
        } else {
            assert(false)
        }
    }
}

class FeatureDescriptionViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem.init(title: "Back", style: .plain, target: nil, action: nil)
    }
}
