//
//  Senators.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class Senators: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var userId: String?
    var First: String?
    var Last: String?
    var Party: String?
    var Phone: String?
    var State: String?
    var Desc: String?
    var ContactURL: String?
    var Fax: String?
    var Twitter: String?
    
    class func dynamoDBTableName() -> String {

        return "codenamelegup-mobilehub-417813871-Senators"
    }
    
    class func hashKeyAttribute() -> String {

        return "userId"
    }
    
}
