//
//  SenatorsTable.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB
import AWSMobileHubHelper

class SenatorsTable: NSObject, Table {
    
    var tableName: String
    var partitionKeyName: String
    var partitionKeyType: String
    var sortKeyName: String?
    var sortKeyType: String?
    var model: AWSDynamoDBObjectModel
    var indexes: [Index]
    var orderedAttributeKeys: [String] {
        return produceOrderedAttributeKeys(model)
    }
    var tableDisplayName: String {

        return "Senators"
    }
    
    override init() {

        model = Senators()
        
        tableName = model.classForCoder.dynamoDBTableName()
        partitionKeyName = model.classForCoder.hashKeyAttribute()
        partitionKeyType = "String"
        indexes = [

            SenatorsLast(),

            SenatorsState(),

            SenatorsFirst(),
        ]
        if let sortKeyNamePossible = model.classForCoder.rangeKeyAttribute?() {
            sortKeyName = sortKeyNamePossible
        }
        super.init()
    }
    
    /**
     * Converts the attribute name from data object format to table format.
     *
     * - parameter dataObjectAttributeName: data object attribute name
     * - returns: table attribute name
     */

    func tableAttributeName(_ dataObjectAttributeName: String) -> String {
        return Senators.jsonKeyPathsByPropertyKey()[dataObjectAttributeName] as! String
    }
    
    func getItemDescription() -> String {
        if let hashKeyValue = AWSIdentityManager.default().identityId
        {
            return "Find Item with userId = \(hashKeyValue)."
        }
        return ""
    }
    
    func getItemWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBObjectModel?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        objectMapper.load(Senators.self, hashKey: AWSIdentityManager.default().identityId!, rangeKey: nil) { (response: AWSDynamoDBObjectModel?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as NSError?)
            })
        }
    }
    
    func scanDescription() -> String {
        return "Show all items in the table."
    }
    
    func scanWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let scanExpression = AWSDynamoDBScanExpression()
        scanExpression.limit = 5

        objectMapper.scan(Senators.self, expression: scanExpression) { (response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as NSError?)
            })
        }
    }
    
    func scanWithFilterDescription() -> String {
        let scanFilterValue = "demo-Party-500000"
        return "Find all items with Party < \(scanFilterValue)."
    }
    
    func scanWithFilterWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let scanExpression = AWSDynamoDBScanExpression()
        
        scanExpression.filterExpression = "#party < :party"
        scanExpression.expressionAttributeNames = ["#party": "Party" ,]
        scanExpression.expressionAttributeValues = [":party": "demo-Party-500000" ,]

        objectMapper.scan(Senators.self, expression: scanExpression) { (response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as? NSError)
            })
        }
    }
    
    func insertSampleDataWithCompletionHandler(_ completionHandler: @escaping (_ errors: [NSError]?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        var errors: [NSError] = []
        let group: DispatchGroup = DispatchGroup()
        let numberOfObjects = 20
        

        let itemForGet: Senators! = Senators()
        
        itemForGet._userId = AWSIdentityManager.default().identityId!
        itemForGet._first = NoSQLSampleDataGenerator.randomPartitionSampleStringWithAttributeName("First")
        itemForGet._last = NoSQLSampleDataGenerator.randomPartitionSampleStringWithAttributeName("Last")
        itemForGet._party = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("Party")
        itemForGet._phone = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("Phone")
        itemForGet._state = NoSQLSampleDataGenerator.randomPartitionSampleStringWithAttributeName("State")
        
        
        group.enter()
        

        objectMapper.save(itemForGet, completionHandler: {(error: Error?) -> Void in
            if let error = error as? NSError {
                DispatchQueue.main.async(execute: {
                    errors.append(error)
                })
            }
            group.leave()
        })
        
        for _ in 1..<numberOfObjects {

            let item: Senators = Senators()
            item._userId = AWSIdentityManager.default().identityId!
            item._first = NoSQLSampleDataGenerator.randomPartitionSampleStringWithAttributeName("First")
            item._last = NoSQLSampleDataGenerator.randomPartitionSampleStringWithAttributeName("Last")
            item._party = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("Party")
            item._phone = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("Phone")
            item._state = NoSQLSampleDataGenerator.randomPartitionSampleStringWithAttributeName("State")
            
            group.enter()
            
            objectMapper.save(item, completionHandler: {(error: Error?) -> Void in
                if error != nil {
                    DispatchQueue.main.async(execute: {
                        errors.append(error! as NSError)
                    })
                }
                group.leave()
            })
        }
        
        group.notify(queue: DispatchQueue.main, execute: {
            if errors.count > 0 {
                completionHandler(errors)
            }
            else {
                completionHandler(nil)
            }
        })
    }
    
    func removeSampleDataWithCompletionHandler(_ completionHandler: @escaping ([NSError]?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        queryExpression.keyConditionExpression = "#userId = :userId"
        queryExpression.expressionAttributeNames = ["#userId": "userId"]
        queryExpression.expressionAttributeValues = [":userId": AWSIdentityManager.default().identityId!,]

        objectMapper.query(Senators.self, expression: queryExpression) { (response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            if let error = error as? NSError {
                DispatchQueue.main.async(execute: {
                    completionHandler([error]);
                    })
            } else {
                var errors: [NSError] = []
                let group: DispatchGroup = DispatchGroup()
                for item in response!.items {
                    group.enter()
                    objectMapper.remove(item, completionHandler: {(error: Error?) in
                        if let error = error as? NSError {
                            DispatchQueue.main.async(execute: {
                                errors.append(error)
                            })
                        }
                        group.leave()
                    })
                }
                group.notify(queue: DispatchQueue.main, execute: {
                    if errors.count > 0 {
                        completionHandler(errors)
                    }
                    else {
                        completionHandler(nil)
                    }
                })
            }
        }
    }
    
    func updateItem(_ item: AWSDynamoDBObjectModel, completionHandler: @escaping (_ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        

        let itemToUpdate: Senators = item as! Senators
        
        itemToUpdate._first = NoSQLSampleDataGenerator.randomPartitionSampleStringWithAttributeName("First")
        itemToUpdate._last = NoSQLSampleDataGenerator.randomPartitionSampleStringWithAttributeName("Last")
        itemToUpdate._party = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("Party")
        itemToUpdate._phone = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("Phone")
        itemToUpdate._state = NoSQLSampleDataGenerator.randomPartitionSampleStringWithAttributeName("State")
        
        objectMapper.save(itemToUpdate, completionHandler: {(error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(error as? NSError)
            })
        })
    }
    
    func removeItem(_ item: AWSDynamoDBObjectModel, completionHandler: @escaping (_ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        
        objectMapper.remove(item, completionHandler: {(error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(error as? NSError)
            })
        })
    }
}

class SenatorsLast: NSObject, Index {
    
    var indexName: String? {

        return "Last"
    }
    
    func supportedOperations() -> [String] {
        return [
            QueryWithPartitionKey,
            QueryWithPartitionKeyAndFilter,
        ]
    }
    
    func queryWithPartitionKeyDescription() -> String {
        let partitionKeyValue = "demo-Last-3"
        return "Find all items with Last = \(partitionKeyValue)."
    }
    
    func queryWithPartitionKeyWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "Last"
        queryExpression.keyConditionExpression = "#last = :last"
        queryExpression.expressionAttributeNames = ["#last": "Last",]
        queryExpression.expressionAttributeValues = [":last": "demo-Last-3",]

        objectMapper.query(Senators.self, expression: queryExpression) { (response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as? NSError)
            })
        }
    }
    
    func queryWithPartitionKeyAndFilterDescription() -> String {
        let partitionKeyValue = "demo-Last-3"
        let filterAttributeValue = "demo-Party-500000"
        return "Find all items with Last = \(partitionKeyValue) and Party > \(filterAttributeValue)."
    }
    
    func queryWithPartitionKeyAndFilterWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "Last"
        queryExpression.keyConditionExpression = "#last = :last"
        queryExpression.filterExpression = "#party > :party"
        queryExpression.expressionAttributeNames = [
            "#last": "Last",
            "#party": "Party",
        ]
        queryExpression.expressionAttributeValues = [
            ":last": "demo-Last-3",
            ":party": "demo-Party-500000",
        ]
        

        objectMapper.query(Senators.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as? NSError)
            })
        })
    }
    
}

class SenatorsState: NSObject, Index {
    
    var indexName: String? {

        return "State"
    }
    
    func supportedOperations() -> [String] {
        return [
            QueryWithPartitionKey,
            QueryWithPartitionKeyAndFilter,
        ]
    }
    
    func queryWithPartitionKeyDescription() -> String {
        let partitionKeyValue = "Alabama"
        return "Find all items with State = \(partitionKeyValue)."
    }
    
    func queryWithPartitionKeyWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "State"
        queryExpression.keyConditionExpression = "#state = :state"
        queryExpression.expressionAttributeNames = ["#state": "State",]
        queryExpression.expressionAttributeValues = [":state": "Alabama",]

        objectMapper.query(Senators.self, expression: queryExpression) { (response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as? NSError)
            })
        }
    }
    
    func queryWithPartitionKeyAndFilterDescription() -> String {
        let partitionKeyValue = "demo-State-3"
        let filterAttributeValue = "demo-Party-500000"
        return "Find all items with State = \(partitionKeyValue) and Party > \(filterAttributeValue)."
    }
    
    func queryWithPartitionKeyAndFilterWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "State"
        queryExpression.keyConditionExpression = "#state = :state"
        queryExpression.filterExpression = "#party > :party"
        queryExpression.expressionAttributeNames = [
            "#state": "State",
            "#party": "Party",
        ]
        queryExpression.expressionAttributeValues = [
            ":state": "demo-State-3",
            ":party": "demo-Party-500000",
        ]
        

        objectMapper.query(Senators.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as? NSError)
            })
        })
    }
    
}

class SenatorsFirst: NSObject, Index {
    
    var indexName: String? {

        return "First"
    }
    
    func supportedOperations() -> [String] {
        return [
            QueryWithPartitionKey,
            QueryWithPartitionKeyAndFilter,
        ]
    }
    
    func queryWithPartitionKeyDescription() -> String {
        let partitionKeyValue = "demo-First-3"
        return "Find all items with First = \(partitionKeyValue)."
    }
    
    func queryWithPartitionKeyWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "First"
        queryExpression.keyConditionExpression = "#first = :first"
        queryExpression.expressionAttributeNames = ["#first": "First",]
        queryExpression.expressionAttributeValues = [":first": "demo-First-3",]

        objectMapper.query(Senators.self, expression: queryExpression) { (response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as? NSError)
            })
        }
    }
    
    func queryWithPartitionKeyAndFilterDescription() -> String {
        let partitionKeyValue = "demo-First-3"
        let filterAttributeValue = "demo-Party-500000"
        return "Find all items with First = \(partitionKeyValue) and Party > \(filterAttributeValue)."
    }
    
    func queryWithPartitionKeyAndFilterWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "First"
        queryExpression.keyConditionExpression = "#first = :first"
        queryExpression.filterExpression = "#party > :party"
        queryExpression.expressionAttributeNames = [
            "#first": "First",
            "#party": "Party",
        ]
        queryExpression.expressionAttributeValues = [
            ":first": "demo-First-3",
            ":party": "demo-Party-500000",
        ]
        

        objectMapper.query(Senators.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: Error?) in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error as? NSError)
            })
        })
    }
    
}
